name: Next.js Sync from Unity

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Sync Unity Build to Next.js Public Folder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Unity Repository
        uses: actions/checkout@v2
        with:
          repository: TRohit20/Assignment-Unity-Repo
          path: unity-repo

      - name: Create Directory for Unity Build
        run: mkdir -p frontend/public/build

      - name: Copy Unity Build
        run: cp -r unity-repo/Hello\ World/build/* frontend/public/build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit Unity Changes to Next.js Repo
        run: |
          cd frontend
          git add .
          git commit -m "Sync Unity build to Next.js public folder"
          git push https://github.com/TRohit20/Assignment-Next.js-Repo.git HEAD:main
        env:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
