name: Next.js Sync from Unity

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Next.js Project and Sync from Unity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.0

      - name: Install Dependencies
        run: npm install

      - name: Copy Unity Build
        run: |
          # Copy Unity build files from Unity repository to public folder in Next.js repository
          git clone https://github.com/TRohit20/Assignment-Unity-Repo.git tmp-unity-repo
          cp -r tmp-unity-repo/Hello\ World/build/* ./public/unity_build
          rm -rf tmp-unity-repo

      - name: Build Next.js
        run: npm run build

      - name: Commit Unity Changes to Next.js Repo
        run: |
          # Commit and push changes to Next.js repository
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Sync Unity build to Next.js public folder"
          git push
